// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: video/video_service.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrecreateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VideoUuid       string                 `protobuf:"bytes,1,opt,name=video_uuid,json=videoUuid,proto3" json:"video_uuid,omitempty"`
	UploadVideoUuid string                 `protobuf:"bytes,2,opt,name=upload_video_uuid,json=uploadVideoUuid,proto3" json:"upload_video_uuid,omitempty"`
	UserUuid        string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CoverUrl        string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	TaskUuid        string                 `protobuf:"bytes,7,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PrecreateRequest) Reset() {
	*x = PrecreateRequest{}
	mi := &file_video_video_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecreateRequest) ProtoMessage() {}

func (x *PrecreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecreateRequest.ProtoReflect.Descriptor instead.
func (*PrecreateRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{0}
}

func (x *PrecreateRequest) GetVideoUuid() string {
	if x != nil {
		return x.VideoUuid
	}
	return ""
}

func (x *PrecreateRequest) GetUploadVideoUuid() string {
	if x != nil {
		return x.UploadVideoUuid
	}
	return ""
}

func (x *PrecreateRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *PrecreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PrecreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PrecreateRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *PrecreateRequest) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

type PrecreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VideoUuid     string                 `protobuf:"bytes,3,opt,name=video_uuid,json=videoUuid,proto3" json:"video_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecreateResponse) Reset() {
	*x = PrecreateResponse{}
	mi := &file_video_video_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecreateResponse) ProtoMessage() {}

func (x *PrecreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecreateResponse.ProtoReflect.Descriptor instead.
func (*PrecreateResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{1}
}

func (x *PrecreateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrecreateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PrecreateResponse) GetVideoUuid() string {
	if x != nil {
		return x.VideoUuid
	}
	return ""
}

type UpdateTranscodeResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUuid     string                 `protobuf:"bytes,1,opt,name=video_uuid,json=videoUuid,proto3" json:"video_uuid,omitempty"`
	TaskUuid      string                 `protobuf:"bytes,2,opt,name=task_uuid,json=taskUuid,proto3" json:"task_uuid,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	DurationSec   int32                  `protobuf:"varint,6,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTranscodeResultRequest) Reset() {
	*x = UpdateTranscodeResultRequest{}
	mi := &file_video_video_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTranscodeResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTranscodeResultRequest) ProtoMessage() {}

func (x *UpdateTranscodeResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTranscodeResultRequest.ProtoReflect.Descriptor instead.
func (*UpdateTranscodeResultRequest) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTranscodeResultRequest) GetVideoUuid() string {
	if x != nil {
		return x.VideoUuid
	}
	return ""
}

func (x *UpdateTranscodeResultRequest) GetTaskUuid() string {
	if x != nil {
		return x.TaskUuid
	}
	return ""
}

func (x *UpdateTranscodeResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTranscodeResultRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *UpdateTranscodeResultRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *UpdateTranscodeResultRequest) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *UpdateTranscodeResultRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type UpdateTranscodeResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTranscodeResultResponse) Reset() {
	*x = UpdateTranscodeResultResponse{}
	mi := &file_video_video_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTranscodeResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTranscodeResultResponse) ProtoMessage() {}

func (x *UpdateTranscodeResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_video_video_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTranscodeResultResponse.ProtoReflect.Descriptor instead.
func (*UpdateTranscodeResultResponse) Descriptor() ([]byte, []int) {
	return file_video_video_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTranscodeResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateTranscodeResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_video_video_service_proto protoreflect.FileDescriptor

const file_video_video_service_proto_rawDesc = "" +
	"\n" +
	"\x19video/video_service.proto\x12\x05video\"\xec\x01\n" +
	"\x10PrecreateRequest\x12\x1d\n" +
	"\n" +
	"video_uuid\x18\x01 \x01(\tR\tvideoUuid\x12*\n" +
	"\x11upload_video_uuid\x18\x02 \x01(\tR\x0fuploadVideoUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\ttask_uuid\x18\a \x01(\tR\btaskUuid\"f\n" +
	"\x11PrecreateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"video_uuid\x18\x03 \x01(\tR\tvideoUuid\"\xee\x01\n" +
	"\x1cUpdateTranscodeResultRequest\x12\x1d\n" +
	"\n" +
	"video_uuid\x18\x01 \x01(\tR\tvideoUuid\x12\x1b\n" +
	"\ttask_uuid\x18\x02 \x01(\tR\btaskUuid\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12!\n" +
	"\fduration_sec\x18\x06 \x01(\x05R\vdurationSec\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\"S\n" +
	"\x1dUpdateTranscodeResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb2\x01\n" +
	"\fVideoService\x12>\n" +
	"\tPrecreate\x12\x17.video.PrecreateRequest\x1a\x18.video.PrecreateResponse\x12b\n" +
	"\x15UpdateTranscodeResult\x12#.video.UpdateTranscodeResultRequest\x1a$.video.UpdateTranscodeResultResponseB\x1bZ\x19video-service/proto/videob\x06proto3"

var (
	file_video_video_service_proto_rawDescOnce sync.Once
	file_video_video_service_proto_rawDescData []byte
)

func file_video_video_service_proto_rawDescGZIP() []byte {
	file_video_video_service_proto_rawDescOnce.Do(func() {
		file_video_video_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_video_service_proto_rawDesc), len(file_video_video_service_proto_rawDesc)))
	})
	return file_video_video_service_proto_rawDescData
}

var file_video_video_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_video_video_service_proto_goTypes = []any{
	(*PrecreateRequest)(nil),              // 0: video.PrecreateRequest
	(*PrecreateResponse)(nil),             // 1: video.PrecreateResponse
	(*UpdateTranscodeResultRequest)(nil),  // 2: video.UpdateTranscodeResultRequest
	(*UpdateTranscodeResultResponse)(nil), // 3: video.UpdateTranscodeResultResponse
}
var file_video_video_service_proto_depIdxs = []int32{
	0, // 0: video.VideoService.Precreate:input_type -> video.PrecreateRequest
	2, // 1: video.VideoService.UpdateTranscodeResult:input_type -> video.UpdateTranscodeResultRequest
	1, // 2: video.VideoService.Precreate:output_type -> video.PrecreateResponse
	3, // 3: video.VideoService.UpdateTranscodeResult:output_type -> video.UpdateTranscodeResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_video_service_proto_init() }
func file_video_video_service_proto_init() {
	if File_video_video_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_video_service_proto_rawDesc), len(file_video_video_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_video_service_proto_goTypes,
		DependencyIndexes: file_video_video_service_proto_depIdxs,
		MessageInfos:      file_video_video_service_proto_msgTypes,
	}.Build()
	File_video_video_service_proto = out.File
	file_video_video_service_proto_goTypes = nil
	file_video_video_service_proto_depIdxs = nil
}
