apiVersion: batch/v1 # Job API 版本
kind: Job # 初始化数据库的任务
metadata:
  name: mysql-init # Job 名称
  namespace: go-video # 命名空间
spec:
  template:
    spec:
      restartPolicy: OnFailure # 失败时重试
      containers:
        - name: mysql-init # 容器名称
          image: mysql:8.0 # 使用官方 MySQL 镜像执行客户端
          env:
            - name: MYSQL_ROOT_PASSWORD # 连接 MySQL 的 root 密码
              value: "jiangqiao"
          command: ["sh","-c","mysql -h mysql -P 3306 -u root -p$MYSQL_ROOT_PASSWORD < /scripts/init_all.sql"] # 执行初始化 SQL
          volumeMounts:
            - name: sql # 挂载包含 SQL 的卷
              mountPath: /scripts # SQL 文件挂载路径
      volumes:
        - name: sql # 卷名称
          configMap:
            name: mysql-init-sql # 提供 SQL 的 ConfigMap
