mirrors: # containerd/ctr 镜像加速配置
  "docker.io": # Docker Hub 主域
    endpoint:
      - "https://docker.m.daocloud.io" # 镜像加速地址
  "registry-1.docker.io": # Docker Hub 备用域
    endpoint:
      - "https://docker.m.daocloud.io" # 镜像加速地址
  "rancher.mirrored-pause": # K3s pause 镜像
    endpoint:
      - "https://docker.m.daocloud.io" # 镜像加速地址
