services:
  upload-service:
    build:
      context: ..
      dockerfile: upload-service/Dockerfile
    container_name: upload-service
    environment:
      CONFIG_PATH: /app/configs/config.dev.yaml
    ports:
      - "8082:8082"
      - "9094:9094"
    volumes:
      - ./configs/config.dev.yaml:/app/configs/config.dev.yaml:ro
    networks:
      - upload_net

networks:
  upload_net:
    driver: bridge