# 生产环境配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"  # debug, release, test
  read_timeout: 30s
  write_timeout: 30s

database:
  host: "${DB_HOST}"
  port: 3306
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_NAME}"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 3600s

redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 20
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

jwt:
  secret: "${JWT_SECRET}"
  expire_time: 2h
  refresh_expire_time: 168h  # 7 days

log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "file"  # stdout, file
  file_path: "/var/log/go-video/app.log"
  max_size: 100  # MB
  max_backups: 30
  max_age: 90  # days
  compress: true

storage:
  type: "aws_s3"  # minio, aws_s3, local
  endpoint: "${S3_ENDPOINT}"
  access_key: "${S3_ACCESS_KEY}"
  secret_key: "${S3_SECRET_KEY}"
  bucket: "${S3_BUCKET}"
  use_ssl: true
  region: "${S3_REGION}"

message_queue:
  type: "rabbitmq"  # rabbitmq, kafka
  url: "${MQ_URL}"
  exchange: "go-video-prod"
  queue_prefix: "go-video-prod"

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  check_origin: false  # 生产环境严格检查来源
  heartbeat_interval: 30s

rate_limit:
  enabled: true
  requests_per_minute: 60
  burst: 5

cors:
  allowed_origins:
    - "https://yourdomain.com"
    - "https://www.yourdomain.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
  max_age: 86400

monitoring:
  metrics_enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  pprof_enabled: false  # 生产环境关闭pprof