// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// 	protoc-gen-go-grpc v1.5.8
// 	protoc              v6.32.1
// source: transcode/transcode_service.proto

package transcode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.56 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscodeService_CreateTranscodeTask_FullMethodName = "/transcode.TranscodeService/CreateTranscodeTask"
	TranscodeService_GetTranscodeTask_FullMethodName    = "/transcode.TranscodeService/GetTranscodeTask"
)

// TranscodeServiceClient is the client API for TranscodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream.
type TranscodeServiceClient interface {
	CreateTranscodeTask(ctx context.Context, in *CreateTranscodeTaskRequest, opts ...grpc.CallOption) (*CreateTranscodeTaskResponse, error)
	GetTranscodeTask(ctx context.Context, in *GetTranscodeTaskRequest, opts ...grpc.CallOption) (*GetTranscodeTaskResponse, error)
}

type transcodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscodeServiceClient(cc grpc.ClientConnInterface) TranscodeServiceClient {
	return &transcodeServiceClient{cc}
}

func (c *transcodeServiceClient) CreateTranscodeTask(ctx context.Context, in *CreateTranscodeTaskRequest, opts ...grpc.CallOption) (*CreateTranscodeTaskResponse, error) {
	out := new(CreateTranscodeTaskResponse)
	err := c.cc.Invoke(ctx, TranscodeService_CreateTranscodeTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetTranscodeTask(ctx context.Context, in *GetTranscodeTaskRequest, opts ...grpc.CallOption) (*GetTranscodeTaskResponse, error) {
	out := new(GetTranscodeTaskResponse)
	err := c.cc.Invoke(ctx, TranscodeService_GetTranscodeTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscodeServiceServer is the server API for TranscodeService service.
// All implementations must embed UnimplementedTranscodeServiceServer
// for forward compatibility.
type TranscodeServiceServer interface {
	CreateTranscodeTask(context.Context, *CreateTranscodeTaskRequest) (*CreateTranscodeTaskResponse, error)
	GetTranscodeTask(context.Context, *GetTranscodeTaskRequest) (*GetTranscodeTaskResponse, error)
	mustEmbedUnimplementedTranscodeServiceServer()
}

// UnimplementedTranscodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTranscodeServiceServer struct {
}

func (UnimplementedTranscodeServiceServer) CreateTranscodeTask(context.Context, *CreateTranscodeTaskRequest) (*CreateTranscodeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTranscodeTask not implemented")
}
func (UnimplementedTranscodeServiceServer) GetTranscodeTask(context.Context, *GetTranscodeTaskRequest) (*GetTranscodeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranscodeTask not implemented")
}
func (UnimplementedTranscodeServiceServer) mustEmbedUnimplementedTranscodeServiceServer() {}

// UnsafeTranscodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscodeServiceServer will
// result in compilation errors.
type UnsafeTranscodeServiceServer interface {
	mustEmbedUnimplementedTranscodeServiceServer()
}

func RegisterTranscodeServiceServer(s grpc.ServiceRegistrar, srv TranscodeServiceServer) {
	s.RegisterService(&TranscodeService_ServiceDesc, srv)
}

func _TranscodeService_CreateTranscodeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTranscodeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).CreateTranscodeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_CreateTranscodeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).CreateTranscodeTask(ctx, req.(*CreateTranscodeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetTranscodeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscodeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetTranscodeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetTranscodeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetTranscodeTask(ctx, req.(*GetTranscodeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscodeService_ServiceDesc is the grpc.ServiceDesc for TranscodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcode.TranscodeService",
	HandlerType: (*TranscodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTranscodeTask",
			Handler:    _TranscodeService_CreateTranscodeTask_Handler,
		},
		{
			MethodName: "GetTranscodeTask",
			Handler:    _TranscodeService_GetTranscodeTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transcode/transcode_service.proto",
}
