apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway
  namespace: observability
  labels:
    release: kps # 对应 kube-prometheus-stack 的 release 选择器
spec:
  namespaceSelector:
    matchNames:
      - go-video
  selector:
    matchLabels:
      app: gateway
  endpoints:
    - port: admin-8001
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upload-service
  namespace: observability
  labels:
    release: kps # 对应 kube-prometheus-stack 的 release 选择器
spec:
  namespaceSelector:
    matchNames:
      - go-video
  selector:
    matchLabels:
      app: upload-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
